name: whispernote
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.10
  - aom=3.6.1
  - asttokens=2.2.1
  - attr=2.5.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.20.1
  - ca-certificates=2023.7.22
  - cairo=1.18.0
  - certifi=2023.7.22
  - charset-normalizer=3.2.0
  - comm=0.1.4
  - contourpy=1.1.0
  - cycler=0.11.0
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.6.8
  - decorator=5.1.1
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=6.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.42.1
  - freeglut=3.2.2
  - freetype=2.12.1
  - fribidi=1.0.10
  - gettext=0.21.1
  - glib=2.78.0
  - glib-tools=2.78.0
  - gmp=6.2.1
  - gnutls=3.7.8
  - graphite2=1.3.13
  - gst-plugins-base=1.22.6
  - gstreamer=1.22.6
  - harfbuzz=8.2.1
  - hdf5=1.14.2
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - ipykernel=6.25.1
  - ipython=8.14.0
  - jasper=4.0.0
  - jedi=0.19.0
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.69
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=8.4.0
  - libdeflate=1.19
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.1.0
  - libgcrypt=1.10.1
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.78.0
  - libglu=9.0.0
  - libgomp=13.1.0
  - libgpg-error=1.47
  - libhwloc=2.9.3
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.23
  - libopenvino=2023.1.0
  - libopenvino-auto-batch-plugin=2023.1.0
  - libopenvino-auto-plugin=2023.1.0
  - libopenvino-hetero-plugin=2023.1.0
  - libopenvino-intel-cpu-plugin=2023.1.0
  - libopenvino-intel-gpu-plugin=2023.1.0
  - libopenvino-ir-frontend=2023.1.0
  - libopenvino-onnx-frontend=2023.1.0
  - libopenvino-paddle-frontend=2023.1.0
  - libopenvino-pytorch-frontend=2023.1.0
  - libopenvino-tensorflow-frontend=2023.1.0
  - libopenvino-tensorflow-lite-frontend=2023.1.0
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=16.0
  - libprotobuf=4.24.3
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.43.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libsystemd0=254
  - libtasn1=4.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.20.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.6.0
  - libxml2=2.11.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mpg123=1.31.3
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.8.1
  - nspr=4.35
  - nss=3.94
  - numpy=1.25.2
  - ocl-icd=2.3.1
  - ocl-icd-system=1.0.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.4
  - p11-kit=0.24.1
  - packaging=23.1
  - pandas=2.1.0
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.1.0
  - pip=23.2.1
  - pixman=0.42.2
  - platformdirs=3.10.0
  - ply=3.11
  - pooch=1.7.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.13
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - pygments=2.16.1
  - pyparsing=3.0.9
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyzmq=25.1.1
  - qt-main=5.15.8
  - readline=8.2
  - requests=2.31.0
  - scipy=1.11.3
  - setuptools=68.1.2
  - sip=6.7.11
  - six=1.16.0
  - snappy=1.1.10
  - stack_data=0.6.2
  - svt-av1=1.7.0
  - tbb=2021.10.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=2.0.4
  - wcwidth=0.2.6
  - wheel=0.41.2
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.39
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - alembic==1.12.1
      - antlr4-python3-runtime==4.9.3
      - asteroid-filterbanks==0.4.0
      - async-timeout==4.0.3
      - attrs==23.1.0
      - audioread==3.0.1
      - cffi==1.16.0
      - click==8.1.7
      - cmake==3.27.7
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.7.0
      - docopt==0.6.2
      - einops==0.7.0
      - filelock==3.12.4
      - flatbuffers==23.5.26
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - greenlet==3.0.1
      - huggingface-hub==0.18.0
      - humanfriendly==10.0
      - hyperpyyaml==1.2.2
      - jinja2==3.1.2
      - joblib==1.3.2
      - julius==0.2.7
      - lazy-loader==0.3
      - librosa==0.10.1
      - lightning==2.1.0
      - lightning-utilities==0.9.0
      - lit==17.0.3
      - llvmlite==0.41.1
      - mako==1.2.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - more-itertools==10.1.0
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - networkx==3.2
      - numba==0.58.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.52
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - onnxruntime-gpu==1.16.1
      - openai-whisper==20230918
      - optuna==3.4.0
      - pip-autoremove==0.10.0
      - primepy==1.3
      - protobuf==4.24.4
      - pyannote-audio==3.0.1
      - pyannote-core==5.0.0
      - pyannote-database==5.0.1
      - pyannote-metrics==3.2.1
      - pyannote-pipeline==3.0.1
      - pycparser==2.21
      - pyfiglet==1.0.2
      - pytorch-lightning==2.1.0
      - pytorch-metric-learning==2.3.0
      - pyyaml==6.0.1
      - regex==2023.10.3
      - rich==13.6.0
      - ruamel-yaml==0.18.2
      - ruamel-yaml-clib==0.2.8
      - scikit-learn==1.3.2
      - semver==3.0.2
      - sentencepiece==0.1.99
      - shellingham==1.5.4
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - soxr==0.3.7
      - speechbrain==0.5.15
      - sqlalchemy==2.0.22
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.2.0
      - tiktoken==0.3.3
      - torch==2.0.0
      - torch-audiomentations==0.11.0
      - torch-pitch-shift==1.2.4
      - torchaudio==2.0.1
      - torchmetrics==1.2.0
      - tqdm==4.66.1
      - triton==2.0.0
      - typer==0.9.0
      - yarl==1.9.2
